# Generated by Django 4.0.6 on 2022-07-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0002_tag_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='ote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='tags',
            field=models.ManyToManyField(blank=True, to='weddings.tag'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
