# Generated by Django 4.0.6 on 2022-07-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0003_wedding_ote_total_wedding_tags_wedding_vote_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
