# Generated by Django 4.0.6 on 2022-07-23 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skill'),
        ('weddings', '0004_wedding_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
